version: 0.1
os: linux
files:
  - source: /fetchr
    destination: /var/www/html/fetchr
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root 
  ValidateService: 
    - location: scripts/check_server.sh 
      timeout: 300 
      runas: root

