version: 0.0
os: linux
files:
  - source: /index.html # To Show if Deployment is Done , Just a Test HTML Page
    destination: /var/www/html/fetchr
  - source: /fetchrfaisal
    destination: /home/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root 
#  ValidateService: 
#    - location: scripts/check_server.sh 
#      timeout: 300 
#      runas: root

